# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
