# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.FileField(blank=True, default='default.png', upload_to=''),
        ),
    ]
