# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200404_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_homepage',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
