# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-13 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_author_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgSize',
            field=models.CharField(default='', max_length=200),
        ),
    ]
