# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-13 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_imgsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgSize',
            field=models.CharField(default='smallIMG', max_length=200),
        ),
    ]
